export const levels: any = {
  1: {
    1: {
      id: 1,
      upKey: [
        'n_103',
        'n_107',
        'n_107',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
      ],
      downKey: ['n_208', 'n_212'],
      speedLimits: [15, 20],
    },
    2: {
      id: 2,
      upKey: [
        'n_107',
        'n_103',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_107',
        'n_103',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_107',
        'n_107',
        'n_103',
      ],
      downKey: ['n_208', 'n_212'],
      speedLimits: [20, 25],
    },
    3: {
      upKey: [
        'n_103',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_103',
        'n_103',
        'n_107',
        'n_103',
        'n_107',
        'n_107',
        'n_107',
        'n_103',
      ],
      downKey: ['n_208', 'n_212'],
      speedLimits: [25, 30],
    },
  },
};

export const upKeyY: any = {
  n_101: { y: 0, name: 'la_', mainImg: 'five', altImg: 'five' },
  n_102: { y: 0, name: 'si_', mainImg: 'four', altImg: 'four' },
  n_103: { y: 188.161, name: 'do_', mainImg: 'thre', altImg: 'three' },
  n_104: { y: 184.161, name: 're_', mainImg: 'one', altImg: 'one' },
  n_105: { y: 0, name: 'mi_', mainImg: 'one', altImg: 'one' },
  n_106: { y: 0, name: 'fa_', mainImg: 'one', altImg: 'one' },
  n_107: { y: 176.161, name: 'sol_', mainImg: 'one', altImg: 'one' },
  n_108: { y: 0, name: 'la_', mainImg: 'one', altImg: 'one' },
  n_109: { y: 0, name: 'si_', mainImg: 'two', altImg: 'two' },
  n_110: { y: 0, name: 'do_', mainImg: 'two', altImg: 'two' },
  n_111: { y: 0, name: 're_', mainImg: 'two', altImg: 'two' },
  n_112: { y: 0, name: 'mi_', mainImg: 'two', altImg: 'two' },
  n_113: { y: 0, name: 'fa_', mainImg: 'two', altImg: 'two' },
  n_114: { y: 0, name: 'sol_', mainImg: 'two', altImg: 'two' },
  n_115: { y: 0, name: 'la_', mainImg: 'thre', altImg: 'thre' },
  n_116: { y: 0, name: 'si_', mainImg: 'seven', altImg: 'seven' },
  n_117: { y: 0, name: 'do_', mainImg: 'eight_bis', altImg: 'eight' },
};

export const downkeyY = {
  n_201: { y: 0, name: 'do_', mainImg: 'five', altImg: 'five_bis' },
  n_202: { y: 0, name: 're_', mainImg: 'four', altImg: 'four_bis' },
  n_203: { y: 0, name: 'mi_', mainImg: 'thre', altImg: 'six' },
  n_204: { y: 0, name: 'fa_', mainImg: 'one', altImg: 'two' },
  n_205: { y: 0, name: 'sol_', mainImg: 'one', altImg: 'two' },
  n_206: { y: 0, name: 'la_', mainImg: 'one', altImg: 'two' },
  n_207: { y: 0, name: 'si_', mainImg: 'one', altImg: 'two' },
  n_208: { y: 0, name: 'do_', mainImg: 'one', altImg: 'two' },
  n_209: { y: 0, name: 're_', mainImg: 'two', altImg: 'one' },
  n_210: { y: 0, name: 'mi_', mainImg: 'two', altImg: 'one' },
  n_211: { y: 0, name: 'fa_', mainImg: 'two', altImg: 'one' },
  n_212: { y: 0, name: 'sol_', mainImg: 'two', altImg: 'two' },
  n_213: { y: 0, name: 'la_', mainImg: 'two', altImg: 'two' },
  n_214: { y: 0, name: 'si_', mainImg: 'two', altImg: 'two' },
  n_215: { y: 0, name: 'do_', mainImg: 'six', altImg: 'six' },
  n_216: { y: 0, name: 're_', mainImg: 'seven_bis', altImg: 'seven_bis' },
  n_217: { y: 0, name: 'mi_', mainImg: 'eight_bis', altImg: 'eight_bis' },
};
